// Optional integration check: node test/browser-smoke.mjs (requires Google Chrome on macOS).
import { spawn, execFileSync } from 'node:child_process';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { setTimeout as delay } from 'node:timers/promises';
import { createApp } from '../server.mjs';

const root = await mkdtemp(path.join(os.tmpdir(), 'review-browser-'));
let app, chrome, socket;
try {
  const git = (...args) => execFileSync('git', ['-C', root, ...args], { stdio: 'pipe' });
  git('init', '-b', 'main'); git('config', 'user.name', 'Browser Test'); git('config', 'user.email', 'test@example.invalid');
  git('commit', '--allow-empty', '-m', 'Pushed base');
  git('init', '--bare', path.join(root, 'remote.git'));
  git('remote', 'add', 'origin', path.join(root, 'remote.git'));
  git('push', '-u', 'origin', 'main');
  await writeFile(path.join(root, 'example.js'), 'export function sum(values) {\n  return values.reduce((a, b) => a + b);\n}\n');
  const navigationLines = Array.from({ length: 50 }, (_, i) => `navigation line ${i + 1}`);
  await writeFile(path.join(root, 'navigation.txt'), navigationLines.join('\n'));
  git('add', 'example.js', 'navigation.txt'); git('commit', '-m', 'Add sum helper');
  git('branch', 'initial');
  git('branch', '--set-upstream-to=origin/main', 'initial');
  git('branch', 'untracked');
  await writeFile(path.join(root, 'example.js'), 'export function sum(values) {\n  return values.reduce((a, b) => a + b, 0);\n}\n');
  navigationLines[2] = 'changed navigation line';
  navigationLines.splice(35, 1);
  navigationLines.splice(18, 0, 'inserted navigation line');
  await writeFile(path.join(root, 'navigation.txt'), navigationLines.join('\n'));
  git('add', 'example.js', 'navigation.txt'); git('commit', '-m', 'Handle empty arrays');
  app = await createApp({ repoPath: root, dataDir: path.join(root, 'data') });
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${app.server.address().port}`;
  const profile = path.join(root, 'chrome');
  chrome = spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', [
    '--headless=new', '--disable-gpu', '--no-first-run', '--no-default-browser-check',
    '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank',
  ], { stdio: 'ignore' });
  let port;
  for (let attempt = 0; attempt < 100; attempt++) {
    if (chrome.exitCode !== null) throw new Error(`Chrome exited: ${chrome.exitCode}`);
    try { port = (await readFile(path.join(profile, 'DevToolsActivePort'), 'utf8')).split('\n')[0]; break; } catch {}
    await delay(100);
  }
  if (!port) throw new Error('Chrome did not expose debugging port');
  const targets = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
  socket = new WebSocket(targets.find(target => target.type === 'page').webSocketDebuggerUrl);
  await new Promise((resolve, reject) => { socket.addEventListener('open', resolve, { once: true }); socket.addEventListener('error', reject, { once: true }); });
  let id = 0;
  const pending = new Map();
  const errors = [];
  socket.addEventListener('message', event => {
    const data = JSON.parse(event.data);
    if (data.method === 'Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.exception?.description || data.params.exceptionDetails.text);
    if (data.method === 'Log.entryAdded' && data.params.entry.level === 'error') errors.push(data.params.entry.text);
    const request = pending.get(data.id);
    if (request) { pending.delete(data.id); data.error ? request.reject(new Error(data.error.message)) : request.resolve(data.result); }
  });
  const cdp = (method, params = {}) => new Promise((resolve, reject) => {
    const current = ++id;
    const timer = setTimeout(() => { pending.delete(current); reject(new Error(`CDP timeout: ${method}`)); }, 10000);
    pending.set(current, { resolve: result => { clearTimeout(timer); resolve(result); }, reject: error => { clearTimeout(timer); reject(error); } });
    socket.send(JSON.stringify({ id: current, method, params }));
  });
  const evaluate = async expression => {
    const result = await cdp('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
    if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
    return result.result.value;
  };
  const wait = async expression => {
    for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await delay(100); }
    throw new Error(`Browser condition timed out: ${expression}`);
  };
  await cdp('Runtime.enable');
  await cdp('Page.enable');
  await cdp('Log.enable');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1600, height: 1000, deviceScaleFactor: 1, mobile: false });
  await cdp('Page.navigate', { url });
  await wait('document.querySelectorAll(".monaco-editor .line-numbers").length >= 6');
  await wait('document.querySelector(".change-count")?.textContent === "1 处变更"');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden'), true);
  const initialWidth = await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().width');
  assert.ok(initialWidth > 1300, `default editor width: ${initialWidth}`);
  const layout = await evaluate('Object.fromEntries([".workspace",".review",".diff-container",".file-card",".editor-scroll",".monaco-host"].map(s => [s,document.querySelector(s).getBoundingClientRect().height]))');
  assert.ok(layout['.monaco-host'] > 600, JSON.stringify(layout));
  await evaluate('document.querySelector("#toggle-comments").click()');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden'), false);
  assert.ok(await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().width') < initialWidth);
  await evaluate('document.querySelector("#focus-diff").click()');
  assert.equal(await evaluate('document.querySelector(".history").hidden && document.querySelector("#comments-pane").hidden'), true);
  assert.ok(await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().width') > initialWidth);
  assert.equal(await evaluate('[".topbar", "#commit-detail", ".review-toolbar", "#files"].every(selector => document.querySelector(selector).hidden)'), true);
  assert.equal(await evaluate('document.querySelector("#focus-actions").hidden'), false);
  await evaluate('document.querySelector("#focus-comments").click()');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden'), false);
  assert.equal(await evaluate('document.querySelector("#focus-comments").getAttribute("aria-expanded")'), 'true');
  assert.equal(await evaluate('document.querySelector(".topbar").hidden'), true);
  await evaluate('document.querySelector("#focus-comments").click()');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden'), true);
  assert.equal(await evaluate('document.querySelector(".file-card > .editor-tools")'), null);
  assert.equal(await evaluate('!!document.querySelector(".file-header .editor-tools #wrap-lines") && !!document.querySelector(".file-header .editor-tools #collapse-lines")'), true);
  assert.equal(await evaluate('(() => { const title = document.querySelector(".file-title").getBoundingClientRect(); const tools = document.querySelector(".editor-tools").getBoundingClientRect(); return Math.abs((title.top+title.bottom)/2-(tools.top+tools.bottom)/2)<2; })()'), true, 'filename and controls share one row');
  assert.ok(await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().height') > layout['.monaco-host'] + 100);
  await evaluate('document.querySelector("#exit-focus").click()');
  assert.equal(await evaluate('[".topbar", "#commit-detail", ".review-toolbar", "#files"].every(selector => !document.querySelector(selector).hidden)'), true);
  assert.equal(await evaluate('!document.querySelector(".history").hidden && !document.querySelector("#comments-pane").hidden'), true);
  await evaluate('document.querySelector("#toggle-comments").click()');
  const pressFocus = async (repeat = false) => {
    await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'f', code: 'KeyF', text: 'f', windowsVirtualKeyCode: 70, autoRepeat: repeat });
    await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'f', code: 'KeyF' });
  };
  await pressFocus();
  assert.equal(await evaluate('document.querySelector(".workspace").classList.contains("focus-diff")'), true);
  await pressFocus(true);
  assert.equal(await evaluate('document.querySelector(".workspace").classList.contains("focus-diff")'), true, 'holding F does not toggle repeatedly');
  await pressFocus();
  assert.equal(await evaluate('document.querySelector(".workspace").classList.contains("focus-diff")'), false);
  const clickLine = async (side, line, shift = false) => {
    const point = await evaluate(`(() => {
      const pane = document.querySelector('.monaco-diff-editor .editor.${side === 'old' ? 'original' : 'modified'}');
      const number = [...pane.querySelectorAll('.line-numbers')].find(node => node.textContent.trim() === '${line}');
      number.scrollIntoView({block:'center'});
      const box = number.getBoundingClientRect();
      return {x:box.x+box.width/2,y:box.y+box.height/2};
    })()`);
    await cdp('Input.dispatchMouseEvent', { type: 'mousePressed', ...point, button: 'left', clickCount: 1, modifiers: shift ? 8 : 0 });
    await cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', ...point, button: 'left', clickCount: 1, modifiers: shift ? 8 : 0 });
  };
  await evaluate('[...document.querySelectorAll(".file-link")].find(node => node.textContent.startsWith("navigation.txt")).click()');
  await wait('document.querySelector(".change-count")?.textContent === "3 处变更"');
  assert.equal(await evaluate('document.querySelector(".current-change").textContent'), '当前 1 / 3');
  const press = async key => {
    await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key, text: key, code: key === '[' ? 'BracketLeft' : 'BracketRight', windowsVirtualKeyCode: key === '[' ? 219 : 221 });
    await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key, code: key === '[' ? 'BracketLeft' : 'BracketRight' });
  };
  const editorPoint = await evaluate('(() => { const box = document.querySelector(".editor.modified .view-lines").getBoundingClientRect(); return {x:box.x+25,y:box.y+20}; })()');
  await cdp('Input.dispatchMouseEvent', { type: 'mousePressed', ...editorPoint, button: 'left', clickCount: 1 });
  await cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', ...editorPoint, button: 'left', clickCount: 1 });
  assert.equal(await evaluate('!!document.activeElement.closest(".monaco-editor")'), true, 'shortcut test must focus Monaco');
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: '】', code: 'BracketRight', text: '】', windowsVirtualKeyCode: 221 });
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: '】', code: 'BracketRight' });
  await wait('document.querySelector(".current-change").textContent === "当前 2 / 3"');
  await wait('document.querySelector(".review-current-gap") && document.querySelector(".review-current-diff")');
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true, 'navigation does not create a comment');
  await press(']');
  await wait('document.querySelector(".current-change").textContent === "当前 3 / 3"');
  await press(']');
  assert.equal(await evaluate('document.querySelector(".current-change").textContent'), '当前 3 / 3', 'last file does not wrap');
  await press('[');
  await wait('document.querySelector(".current-change").textContent === "当前 2 / 3"');
  await press('[');
  await wait('document.querySelector(".current-change").textContent === "当前 1 / 3"');
  await press('[');
  await wait('document.querySelector(".file-link.active")?.textContent.startsWith("example.js") && document.querySelector(".current-change")?.textContent === "当前 1 / 1"');
  await press('[');
  assert.equal(await evaluate('document.querySelector(".file-link.active").textContent.startsWith("example.js")'), true, 'first file does not wrap');
  await press(']');
  await wait('document.querySelector(".file-link.active")?.textContent.startsWith("navigation.txt") && document.querySelector(".current-change")?.textContent === "当前 1 / 3"');
  await evaluate('document.querySelectorAll(".editor-tools button")[1].click()');
  await wait('document.querySelector(".current-change").textContent === "当前 2 / 3"');
  await clickLine('new', 19);
  const beforeTyping = await evaluate('document.querySelector(".current-change").textContent');
  await evaluate('document.querySelector("#inline-comment-body").focus()');
  await press('['); await press(']');
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: '】', code: 'BracketRight', text: '】', windowsVirtualKeyCode: 221 });
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: '】', code: 'BracketRight' });
  await pressFocus();
  assert.equal(await evaluate('document.querySelector("#inline-comment-body").value'), '[]】f');
  assert.equal(await evaluate('document.querySelector(".workspace").classList.contains("focus-diff")'), false, 'typing F in a comment does not toggle focus');
  assert.equal(await evaluate('document.querySelector(".current-change").textContent'), beforeTyping);
  await evaluate('document.querySelector(".selection-actions button[type=button]").click(); document.querySelector("#branch").focus()');
  await press(']');
  assert.equal(await evaluate('document.querySelector(".current-change").textContent'), beforeTyping);
  await evaluate('[...document.querySelectorAll(".file-link")].find(node => node.textContent.startsWith("example.js")).click()');
  await wait('document.querySelector(".change-count")?.textContent === "1 处变更"');
  assert.equal(await evaluate('document.querySelector(".current-change").textContent'), '当前 1 / 1');
  const editorHeightBeforeSelection = await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().height');
  const dragPoints = await evaluate(`(() => {
    const lines = document.querySelectorAll('.editor.modified .view-lines .view-line');
    return [lines[0], lines[1]].map(line => { const box = line.getBoundingClientRect(); return {x:box.x+24,y:box.y+box.height/2}; });
  })()`);
  await cdp('Input.dispatchMouseEvent', { type: 'mouseMoved', ...dragPoints[0] });
  await cdp('Input.dispatchMouseEvent', { type: 'mousePressed', ...dragPoints[0], button: 'left', clickCount: 1 });
  await cdp('Input.dispatchMouseEvent', { type: 'mouseMoved', ...dragPoints[1], button: 'left', buttons: 1 });
  await cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', ...dragPoints[1], button: 'left', clickCount: 1 });
  await wait('!document.querySelector(".selection-actions").hidden && document.querySelector(".selection-description").textContent.includes("1:4–2:4")');
  await wait('document.activeElement.id === "inline-comment-body"');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".selection-actions")).position'), 'fixed');
  assert.equal(await evaluate('document.querySelector(".monaco-host").getBoundingClientRect().height'), editorHeightBeforeSelection, 'floating composer does not shrink diff');
  assert.equal(await evaluate('document.querySelectorAll(".editor.modified .review-selected-content-text").length > 0 && document.querySelectorAll(".editor.modified .review-selected-line").length === 0'), true, 'precise selection stays highlighted after composer receives focus without whole-line shading');
  assert.notEqual(await evaluate('getComputedStyle(document.querySelector(".review-selected-content")).boxShadow'), 'none', 'selection has a visible outline');
  const popupBounds = await evaluate('(() => {const r=document.querySelector(".selection-actions").getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right};})()');
  assert.ok(Math.abs(popupBounds.top - dragPoints[1].y) < 60, 'composer opens near selected code');
  assert.ok(popupBounds.left >= 0 && popupBounds.right <= 1600 && popupBounds.bottom <= 1000);
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 600, deviceScaleFactor: 1, mobile: true });
  await wait('(() => {const r=document.querySelector(".selection-actions").getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && r.top>=0 && r.bottom<=innerHeight;})()');
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true, 'floating composer does not overflow mobile page');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1600, height: 1000, deviceScaleFactor: 1, mobile: false });
  await wait('document.querySelector(".selection-actions").getBoundingClientRect().width === 380');
  const copiedCode = await evaluate('(() => { const data = new DataTransfer(); const event = new ClipboardEvent("copy", {clipboardData:data,bubbles:true,cancelable:true}); document.activeElement.dispatchEvent(event); return {text:data.getData("text/plain"),handled:event.defaultPrevented}; })()');
  assert.equal(copiedCode.handled, true);
  assert.ok(copiedCode.text.includes('function sum(values) {\n'), 'copy retains exact dragged code across lines');
  assert.ok(!copiedCode.text.includes('reduce'), 'copy does not expand selection to full comment lines');
  await cdp('Browser.grantPermissions', { origin: url, permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'] });
  await cdp('Input.dispatchKeyEvent', { type: 'keyDown', key: 'c', code: 'KeyC', modifiers: 4, commands: ['copy'] });
  await cdp('Input.dispatchKeyEvent', { type: 'keyUp', key: 'c', code: 'KeyC', modifiers: 4 });
  assert.equal(await evaluate('navigator.clipboard.readText()'), copiedCode.text, 'keyboard copy writes the selected code to clipboard');
  await cdp('Input.insertText', { text: '划线后直接输入' });
  assert.equal(await evaluate('(() => { const event = new ClipboardEvent("copy", {clipboardData:new DataTransfer(),bubbles:true,cancelable:true}); document.activeElement.dispatchEvent(event); return event.defaultPrevented; })()'), false, 'comment copying uses native behavior');
  assert.equal(await evaluate('document.querySelector("#inline-comment-body").value'), '划线后直接输入');
  await evaluate('document.querySelector("#inline-comment-body").dispatchEvent(new PointerEvent("pointerdown", {bubbles:true}))');
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), false, 'clicking inside keeps composer open');
  const outside = await evaluate('(() => { const r=document.querySelector(".file-title").getBoundingClientRect(); return {x:r.x+10,y:r.y+r.height/2}; })()');
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...outside, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...outside, button:'left', clickCount:1});
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true, 'outside click dismisses composer');
  assert.equal(await evaluate('document.querySelector("#inline-comment-body").value'), '划线后直接输入', 'dismiss keeps draft');
  await clickLine('new', 1);
  await wait('!document.querySelector(".selection-actions").hidden && document.activeElement.id === "inline-comment-body"');
  assert.equal(await evaluate('document.querySelector("#inline-comment-body").value'), '划线后直接输入', 'selecting again restores draft');
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...dragPoints[0], button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...dragPoints[0], button:'left', clickCount:1});
  await wait('document.querySelector(".selection-actions").hidden');
  await clickLine('new', 1);
  await wait('!document.querySelector(".selection-actions").hidden && document.activeElement.id === "inline-comment-body"');
  await evaluate('document.querySelector(".selection-actions button[type=button]").click()');
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true);
  await clickLine('new', 1);
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), false, 'single line opens composer');
  await wait('document.activeElement.id === "inline-comment-body"');
  await clickLine('new', 2, true);
  await wait('document.querySelector(".selection-description")?.textContent.includes("1–2")');
  await wait('document.activeElement.id === "inline-comment-body"');
  assert.equal(await evaluate('document.querySelectorAll(".editor.original .review-selected-line").length'), 0);
  assert.equal(await evaluate('document.querySelectorAll(".editor-headings").length'), 0);
  assert.equal(await evaluate('document.querySelector(".file-header").nextElementSibling.classList.contains("editor-scroll")'), true);
  await clickLine('old', 2, true);
  assert.match(await evaluate('document.querySelector(".selection-description").textContent'), /新版本.*1–2/);
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true, 'invalid cross-side selection leaves composer dismissed');
  await clickLine('new', 2, true);
  await wait('document.activeElement.id === "inline-comment-body"');
  assert.equal(await evaluate('!document.querySelector(".selection-actions").hidden && !document.querySelector("#comment-dialog").open'), true, 'selection immediately opens inline composer');
  await evaluate('document.querySelector("#inline-comment-body").value="需要空数组测试 <script>alert(1)</script>"; document.querySelector("#inline-comment-body").dispatchEvent(new Event("input"));');
  await clickLine('new', 3);
  assert.match(await evaluate('document.querySelector(".selection-description").textContent'), /1–2/, 'draft retains its anchor');
  await evaluate('document.querySelector("#branch").value="refs/heads/initial"; document.querySelector("#branch").dispatchEvent(new Event("change"));');
  await wait('document.querySelector("#commit-detail h2")?.textContent === "Add sum helper" && document.querySelector(".monaco-editor")');
  await evaluate('document.querySelector("#branch").value="HEAD"; document.querySelector("#branch").dispatchEvent(new Event("change"));');
  await wait('document.querySelector("#inline-comment-body")?.value.includes("需要空数组测试")');
  assert.match(await evaluate('document.querySelector(".selection-description").textContent'), /1–2/);
  await evaluate('document.querySelector("#inline-comment-body").dispatchEvent(new KeyboardEvent("keydown", {key:"Enter",ctrlKey:true,bubbles:true}));');
  await wait('document.querySelectorAll(".comment-card").length === 1');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden'), true, 'saving keeps comments collapsed');
  assert.equal(app.store.list()[0].endLine, 2);
  assert.match(app.store.list()[0].code, /export function sum/);
  assert.equal(await evaluate('document.querySelector(".comment-card script") === null'), true);
  await cdp('Page.reload');
  await wait('document.querySelectorAll(".comment-card").length === 1 && document.querySelector(".change-count")?.textContent === "1 处变更"');
  const codePoint = async (side, line) => evaluate(`(() => {
    const node = document.querySelectorAll('.editor.${side === 'old' ? 'original' : 'modified'} .view-lines .view-line')[${line - 1}];
    const r = node.getBoundingClientRect(); return {x:r.x+24,y:r.y+r.height/2};
  })()`);
  const clickCode = async (side, line) => {
    const point = await codePoint(side, line);
    await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...point, button:'left', clickCount:1});
    await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...point, button:'left', clickCount:1});
  };
  await wait('document.querySelector(".editor.modified .review-comment-underline")');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".review-comment-underline")).textDecorationLine'), 'underline');
  await clickCode('new', 1);
  await wait('!document.querySelector(".comment-preview").hidden');
  assert.match(await evaluate('document.querySelector(".comment-preview").textContent'), /需要空数组测试 <script>alert\(1\)<\/script>/);
  assert.equal(await evaluate('document.querySelector(".comment-preview script")'), null, 'preview treats comment HTML as text');
  assert.equal(await evaluate('document.querySelector("#comments-pane").hidden && document.querySelector(".selection-actions").hidden'), true);
  const insidePreview = await evaluate('(() => { const r=document.querySelector(".comment-preview-item p").getBoundingClientRect(); return {x:r.x+5,y:r.y+5}; })()');
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...insidePreview, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...insidePreview, button:'left', clickCount:1});
  assert.equal(await evaluate('document.querySelector(".comment-preview").hidden'), false, 'inside click keeps preview open');
  await cdp('Emulation.setDeviceMetricsOverride', { width:390, height:600, deviceScaleFactor:1, mobile:true });
  await wait('(() => {const r=document.querySelector(".comment-preview").getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && r.top>=0 && r.bottom<=innerHeight;})()');
  await cdp('Emulation.setDeviceMetricsOverride', { width:1600, height:1000, deviceScaleFactor:1, mobile:false });
  await wait('document.querySelector(".comment-preview").getBoundingClientRect().width === 380');
  await evaluate('document.querySelector(".comment-preview-heading button").click()');
  await clickCode('new', 3);
  assert.equal(await evaluate('document.querySelector(".comment-preview").hidden'), true, 'uncommented code does not open preview');
  const from = await codePoint('new', 1), to = await codePoint('new', 2);
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...from, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseMoved', ...to, button:'left', buttons:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...to, button:'left', clickCount:1});
  await wait('!document.querySelector(".selection-actions").hidden && document.activeElement.id === "inline-comment-body"');
  assert.equal(await evaluate('document.querySelector(".comment-preview").hidden'), true, 'dragging underlined code creates a comment instead of opening preview');
  await cdp('Input.insertText', {text:'重叠评论草稿'});
  await clickCode('new', 1);
  await wait('!document.querySelector(".comment-preview").hidden');
  assert.equal(await evaluate('document.querySelector("#inline-comment-body").value'), '重叠评论草稿', 'viewing saved comments preserves draft');
  await clickLine('new', 1);
  await wait('document.activeElement.id === "inline-comment-body" && !document.querySelector(".selection-actions").hidden');
  assert.equal(await evaluate('document.querySelector(".comment-preview").hidden'), true);
  await evaluate('document.querySelector(".selection-actions").requestSubmit()');
  await wait('document.querySelectorAll(".comment-card").length === 2');
  const exact = app.store.list().find(comment => comment.body === '重叠评论草稿');
  assert.equal(exact.startColumn, 4);
  assert.equal(exact.endColumn, 4);
  assert.equal(exact.code, copiedCode.text, 'stored code is exactly the dragged selection, not full lines');
  await cdp('Page.reload');
  await wait('document.querySelectorAll(".comment-card").length === 2 && document.querySelector(".review-comment-underline")');
  const prefix = await codePoint('new', 1); prefix.x -= 22;
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...prefix, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...prefix, button:'left', clickCount:1});
  await wait('!document.querySelector(".comment-preview").hidden');
  assert.equal(await evaluate('document.querySelectorAll(".comment-preview-item").length'), 1, 'same-line prefix outside exact range matches only legacy whole-line comment');
  await clickCode('new', 2);
  assert.equal(await evaluate('document.querySelectorAll(".comment-preview-item").length'), 1, 'exclusive end column does not match precise comment');
  await clickCode('new', 1);
  await wait('!document.querySelector(".comment-preview").hidden && document.querySelectorAll(".comment-preview-item").length === 2');
  await evaluate('window.confirm=()=>true; document.querySelectorAll(".comment-card")[0].querySelectorAll(".comment-actions button")[2].click()');
  await wait('document.querySelectorAll(".comment-card").length === 1 && document.querySelectorAll(".comment-preview-item").length === 1');
  const titlePoint = await evaluate('(() => {const r=document.querySelector(".file-title").getBoundingClientRect();return {x:r.x+5,y:r.y+5};})()');
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...titlePoint, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...titlePoint, button:'left', clickCount:1});
  assert.equal(await evaluate('document.querySelector(".comment-preview").hidden'), true, 'outside click closes preview');
  const partialStart = await codePoint('new', 1), partialEnd = {...partialStart, x:partialStart.x+48};
  await cdp('Input.dispatchMouseEvent', {type:'mousePressed', ...partialStart, button:'left', clickCount:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseMoved', ...partialEnd, button:'left', buttons:1});
  await cdp('Input.dispatchMouseEvent', {type:'mouseReleased', ...partialEnd, button:'left', clickCount:1});
  await wait('document.activeElement.id === "inline-comment-body" && !document.querySelector(".selection-actions").hidden');
  const partialText = await evaluate('(() => {const data=new DataTransfer();document.activeElement.dispatchEvent(new ClipboardEvent("copy",{clipboardData:data,bubbles:true,cancelable:true}));return data.getData("text/plain");})()');
  await cdp('Input.insertText', {text:'单行精确评论'});
  await evaluate('document.querySelector(".selection-actions").requestSubmit()');
  await wait('document.querySelectorAll(".comment-card").length === 2');
  const partial = app.store.list().find(comment => comment.body === '单行精确评论');
  assert.equal(partial.startLine, partial.endLine);
  assert.equal(partial.startColumn, 4);
  assert.ok(partial.endColumn > partial.startColumn && partial.code.length < 12);
  assert.equal(partial.code, partialText);
  await evaluate('[...document.querySelectorAll(".comment-body-link")].find(node=>node.textContent==="单行精确评论").click()');
  await wait('document.querySelector(".review-selected-content-text")');
  assert.equal((await evaluate('[...document.querySelectorAll(".review-selected-content-text")].map(node=>node.textContent).join("")')).replaceAll(' ', ' '), partialText, 'historical jump highlights only original selected characters');
  await evaluate('document.querySelectorAll(".comment-card")[0].querySelectorAll(".comment-actions button")[2].click()');
  await wait('document.querySelectorAll(".comment-card").length === 1');
  await evaluate('document.querySelector("#toggle-comments").click(); document.querySelector(".comment-actions button").click()');
  await wait('document.querySelectorAll(".comment-card").length === 0');
  assert.equal(app.store.list()[0].resolved, true);
  await wait('document.querySelector(".editor.modified .review-comment-resolved")');
  await clickCode('new', 2);
  await wait('!document.querySelector(".comment-preview").hidden && document.querySelector(".comment-preview-meta").textContent.includes("已解决")');
  assert.equal(await evaluate('document.querySelectorAll(".comment-card").length'), 0, 'preview is independent of sidebar filters');
  await evaluate('document.querySelector("#comment-filter").value="resolved"; document.querySelector("#comment-filter").dispatchEvent(new Event("change"));');
  await wait('document.querySelectorAll(".comment-card").length === 1');
  await evaluate('document.querySelectorAll(".comment-actions button")[1].click(); document.querySelector("#comment-body").value="编辑后的审查意见"; document.querySelector("#comment-form").requestSubmit();');
  await wait('document.querySelector(".comment-body-link")?.textContent === "编辑后的审查意见"');
  await clickLine('old', 2);
  await evaluate('document.querySelector("#comment-filter").value="all"; document.querySelector("#comment-filter").dispatchEvent(new Event("change")); document.querySelector("#inline-comment-body").value="删除行也需要检查"; document.querySelector("#inline-comment-body").dispatchEvent(new Event("input")); document.querySelector(".selection-actions").requestSubmit();');
  await wait('document.querySelectorAll(".comment-card").length === 2');
  assert.equal(app.store.list()[1].side, 'old');
  assert.equal(app.store.list()[1].code, '  return values.reduce((a, b) => a + b);');
  await wait('document.querySelector(".editor.original .review-comment-underline")');
  await clickCode('old', 2);
  await wait('!document.querySelector(".comment-preview").hidden && document.querySelector(".comment-preview").textContent.includes("删除行也需要检查")');
  assert.equal(await evaluate('document.querySelectorAll(".comment-preview-item").length'), 1, 'old and new side comments stay separate');
  await evaluate('document.querySelector("#wrap-lines").click(); document.querySelector("#collapse-lines").click(); document.querySelectorAll(".editor-tools button")[1].click()');
  await evaluate('document.querySelector("#branch").value="refs/heads/initial"; document.querySelector("#branch").dispatchEvent(new Event("change"));');
  await wait('document.querySelector("#commit-detail h2")?.textContent === "Add sum helper" && document.querySelector(".change-count")?.textContent === "1 处变更"');
  assert.equal(await evaluate('document.querySelectorAll(".comment-card").length'), 0);
  assert.equal(await evaluate('document.querySelectorAll(".comment-preview").length === 1 && document.querySelector(".comment-preview").hidden'), true, 'changing commits disposes old preview');
  assert.equal(await evaluate('document.querySelectorAll(".editor-headings").length'), 0);
  await clickLine('old', 1);
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true);
  await evaluate('document.querySelector("#comment-scope").value="all"; document.querySelector("#comment-scope").dispatchEvent(new Event("change")); document.querySelector(".comment-body-link").click();');
  await wait('document.querySelector("#commit-detail h2")?.textContent === "Handle empty arrays" && document.querySelectorAll(".editor.original .review-selected-line").length > 0');
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true, 'comment jump does not open new composer');
  await wait('document.querySelectorAll(".editor.original .review-comment-target").length > 0');
  await evaluate('document.querySelector("#toggle-comments").focus()');
  assert.ok(await evaluate('document.querySelectorAll(".editor.original .review-comment-target").length') > 0, 'comment range stays marked without editor focus');
  await evaluate('window.confirm = () => true; document.querySelectorAll(".comment-actions button")[2].click()');
  await wait('document.querySelectorAll(".comment-card").length === 1');
  assert.equal(app.store.list().length, 1);
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true, 'no horizontal page overflow on mobile');
  await cdp('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
  assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true);
  await evaluate('document.querySelector("#branch").value="refs/heads/untracked"; document.querySelector("#branch").dispatchEvent(new Event("change"));');
  await wait('document.querySelector("#commit-detail").textContent.includes("相对 main")');
  assert.match(await evaluate('document.querySelector(".history-hint").textContent'), /对比本地 main/);
  assert.equal(await evaluate('document.querySelectorAll("#commits .commit").length'), 0);
  assert.equal(await evaluate('[...document.querySelector("#branch").options].some(option => option.value.startsWith("refs/remotes/"))'), false);
  git('push');
  await evaluate('document.querySelector("#branch").value="HEAD"; document.querySelector("#branch").dispatchEvent(new Event("change"));');
  await wait('document.querySelector("#commit-detail").textContent.includes("没有未 push")');
  assert.equal(await evaluate('document.querySelectorAll("#commits .commit").length'), 0);
  await evaluate('document.querySelector(".comment-body-link").click()');
  await wait('document.querySelector("#commit-detail h2")?.textContent === "Handle empty arrays" && document.querySelectorAll(".review-selected-line").length > 0');
  assert.equal(await evaluate('document.querySelector(".selection-actions").hidden'), true);
  const screenshot = await cdp('Page.captureScreenshot', { format: 'png' });
  const screenshotPath = path.join(os.tmpdir(), 'commit-review-browser.png');
  await writeFile(screenshotPath, Buffer.from(screenshot.data, 'base64'));
  assert.deepEqual(errors, []);
  console.log(`Browser smoke passed: multiline comments, persistence, resolve/filter, escaping, responsive layout. Screenshot: ${screenshotPath}`);
} finally {
  socket?.close();
  if (chrome && chrome.exitCode === null) { chrome.kill(); await new Promise(resolve => chrome.once('exit', resolve)); }
  if (app) { await new Promise(resolve => app.server.close(resolve)); await app.release(); }
  await rm(root, { recursive: true, force: true });
}
